

parameters:
    ip_fname: '/global/cfs/cdirs/m3363/vayyar/cosmogan_data/raw_data/3d_data/dataset1_smoothing_const_params_64cube_100k/norm_1_train_val.npy'
    op_loc: '/global/cfs/cdirs/m3363/vayyar/cosmogan_data/results_from_other_code/pytorch/results/3d/'
    image_size: 64
    num_imgs: 20000

    workers: 2 #Number of workers for dataloader
    nc: 1 # Number of channels in the training images. For color images this is 3
    nz: 64 # Size of z latent vector (i.e. size of generator input)
    ngf: 64 # Size of feature maps in generator
    ndf: 64 # Size of feature maps in discriminator
    beta1: 0.5 # Beta1 hyperparam for Adam optimizers
    kernel_size: 5
    stride: 2
    g_padding: 2
    d_padding: 2
    flip_prob: 0.01
    bns: 50

    checkpoint_size: 10
    
    batch_size: 32
    epochs: 30
    learn_rate: 0.0002
    
    deterministic: False
    seed: 234373
    lambda_spec_mean: 1.0
    lambda_spec_var: 1.0
    lambda_fm: 0.0 ## Enter False or float
    lambda_gp: 0.0 ## Enter False or float
    grad_clip: 1.0
    save_steps_list: [5,10]
    run_suffix: train

    description: '3d GAN: DDP with new loss'
