

parameters:
    ip_fname: '/gpfs/alpine/ast153/proj-shared/venkitesh/Cosmogan/data/raw_data/3d_data/64cube/dataset2a_3dcgan_4univs_64cube_simple_splicing'
    op_loc: '/gpfs/alpine/ast153/proj-shared/venkitesh/Cosmogan/data/results_pytorch/3d/'
    image_size: 64
    num_imgs: 40000

    workers: 2 #Number of workers for dataloader
    nc: 1 # Number of channels in the training images. For color images this is 3
    nz: 64 # Size of z latent vector (i.e. size of generator input)
    ngf: 64 # Size of feature maps in generator
    ndf: 64 # Size of feature maps in discriminator
    beta1: 0.5 # Beta1 hyperparam for Adam optimizers
    kernel_size: 5
    stride: 2
    g_padding: 2
    d_padding: 2
    flip_prob: 0.01
    bns: 50
    
    checkpoint_size: 10

    sigma_list: [0.5,0.8,1.1]
    model: 2
    batch_size: 32
    epochs: 250
    learn_rate: 0.00006
    op_size: 32
    
    deterministic: False
    seed: 234373
    lambda_spec_mean: 0.5
    lambda_spec_var: 0.5
    lambda_fm: 0.0 ## Enter False or float
    lambda_gp: 0.0 ## Enter False or float
    grad_clip: 0.5
    save_steps_list: ' '
    run_suffix: cgan_bs32_lr0.00006_nodes8_spec0.5

    description: '3d conditional GAN: DDP with new loss'
