

parameters:
    ip_fname: '/gpfs/alpine/ast153/proj-shared/venkitesh/Cosmogan/data/raw_data/3d_data/128cube/dataset3_smoothing_const_params_128cube/norm_1_train_val.npy'
    op_loc: '/gpfs/alpine/ast153/proj-shared/venkitesh/Cosmogan/data/results_pytorch/3d/'
    image_size: 128
    num_imgs: 90000

    workers: 2 #Number of workers for dataloader
    nc: 1 # Number of channels in the training images. For color images this is 3
    nz: 64 # Size of z latent vector (i.e. size of generator input)
    ngf: 64 # Size of feature maps in generator
    ndf: 64 # Size of feature maps in discriminator
    beta1: 0.5 # Beta1 hyperparam for Adam optimizers
    kernel_size: 5
    stride: 2
    g_padding: 2
    d_padding: 2
    flip_prob: 0.01
    bns: 50

    checkpoint_size: 1
    batch_size: 8
    epochs: 100
    learn_rate: 0.0001
    op_size: 32


    deterministic: False
    seed: 234373
    lambda_spec_mean: 0.1
    lambda_spec_var: 0.1
    lambda_fm: 0.0 ## Enter False or float
    lambda_gp: 0.0 ## Enter False or float
    grad_clip: 1.0
    save_steps_list: [5,10]
    run_suffix: bs8_lr0.0001_nodes8

    description: '3d GAN: DDP with new loss'
