

parameters:
    ip_fname: '/global/cfs/cdirs/m3363/vayyar/cosmogan_data/raw_data/3d_data/dataset4_smoothing_4univ_cgan_varying_sigma_128cube'
    op_loc: '/global/cfs/cdirs/m3363/vayyar/cosmogan_data/results_from_other_code/pytorch/results/3d_cGAN/'
    image_size: 128
    num_imgs: 5000
    ip_fldr: '/global/cfs/cdirs/m3363/vayyar/cosmogan_data/results_from_other_code/pytorch/results/3d_cGAN/20210722_200025_cgan_128_nodes1_lr0.00002_finetune/'
    chkpt_file: '/global/cfs/cdirs/m3363/vayyar/cosmogan_data/results_from_other_code/pytorch/results/3d_cGAN/20210722_200025_cgan_128_nodes1_lr0.00002_finetune/models/checkpoint_last.tar'

    workers: 2 #Number of workers for dataloader
    nc: 1 # Number of channels in the training images. For color images this is 3
    nz: 64 # Size of z latent vector (i.e. size of generator input)
    ngf: 64 # Size of feature maps in generator
    ndf: 64 # Size of feature maps in discriminator
    beta1: 0.5 # Beta1 hyperparam for Adam optimizers
    kernel_size: 5
    stride: 2
    g_padding: 2
    d_padding: 2
    flip_prob: 0.01
    bns: 50
    
    checkpoint_size: 10

    sigma_list: [0.5,0.8,1.1]
    model: 2
    batch_size: 8
    epochs: 300
    op_size: 8
    
    learn_rate_d: 0.000002
    learn_rate_g: 0.000002
    lr_d_epochs: [40,60]
    lr_d_gamma: 1.0
    lr_g_epochs: [40,60]
    lr_g_gamma: 1.0
    
    deterministic: False
    seed: 234373
    lambda_spec_mean: 0.1
    lambda_spec_var: 0.1
    lambda_fm: 50.0 ## Enter False or float
    lambda_gp: 0.0 ## Enter False or float
    grad_clip: 1.0
    save_steps_list: 'all'
    run_suffix: cgan_128_lr0.000002_vary_fm50

    description: '3d conditional GAN 128cube'
